### ISSUE TITLE
Week 3 Disjoint sets quiz

### ISSUE THREAD

**Issue by mr-phenomenal-one** [sudheernaidu53/Data-Structures-and-Algorithms-specialization-University-of-California-San-Diego#1]
Please upload the answer key for disjoint sets in week 3 data struscture course 2. By mistake you have uploaded a wrong file in it

**Comment by mr-phenomenal-one** [comment]
Please get it done today itself. Its the last date.

**Comment by sudheernaidu53** [comment]
I was hopeful that people can refer this repository for doubts and clarifications. Please don't copy. That violates the rules, and moreover this does not help you in learning.

**Comment by sudheernaidu53** [comment]
Have uploaded the correct file now.
